### ISSUE TITLE
Does my app have to be approved in marketplace for dev usage?

### ISSUE THREAD

**Issue by BerndGewehr** [zoom/zoom-bot-api#1]
I get the following error when trying this code:

`{ message: 'The user does not have authorization, the application cannot send the message.',
  code: 7004 }`

My app is not yet approved. I am using the dev credentials and my own userId for the account_id variable. (with ID from from get users, is this correct?)

What else could be wrong? Are only paid accounts allowed to have bots posting? (I'm on that 60 days trial...)

**Comment by michaelZoomDA** [comment]
Hi @BerndGewehr, no your app does not need to be approved. You only submit your app for approval if you want other users to download and use it as well. Can you send a code snippet for us to look at?

**Comment by BerndGewehr** [comment]
I am using exactly the code from this repo.

**Comment by BerndGewehr** [comment]
The 
https://github.com/zoom/zoom-bot-api/blob/master/listChatChannels.js
works as expected with these credentials but sendmessage throws that error.

**Comment by michaelZoomDA** [comment]
@BerndGewehr What is the email associated to the account that you're developing with?

**Comment by BerndGewehr** [comment]
I am using this payload:

```
                                body: { 
                                  robot_jid: 'muiupfenqhilmxq2XXXXXX@xmpp.zoom.us', //located in marketplace, bot JID 
                                  to_jid: 'cdff5f371c204f29af45b09ba1XXXXXX@conference.xmpp.zoom.us', //group jid
                                  account_id: 'B6w7a2W1QyOcQK0pXXXXXX', //user account ID
                                  content: 'My first bot message! (deserve a beer?)' //message to be group  
                                },
```

**Comment by BerndGewehr** [comment]
Now I got it. The missing link was the generation of the URL to use the app WITHOUT submitting it to you. Hard to guess, though!

**Comment by michaelZoomDA** [comment]
Hi @BerndGewehr Glad you were able to resolve the issue, looks like you were using your prod credentials.  I'll make sure update this repo with a note to use the publishable url if you are using the prod credentials.
